### ISSUE TITLE
Update JDA dependency

### ISSUE THREAD

**Issue by MinnDevelopment** [zekroTJA/DiscordBot#1]
I noticed that you are on an ancient version of JDA (3.0.ALPHA) but we actually went through 2 BETA phases and are now on 3.0.0!
Please consider updating as your youtube tutorial seems to attract some new people that have not much experience with maven and dynamic dependencies.

Latest version can be found in our [README](https://github.com/DV8FromTheWorld/JDA/blob/master/README.md#download).
We don't recommend using a different repository than jcenter as it will not always be up-to-date with our changes.

Please also make an annotation in your tutorial to inform people about this.

Regards, the JDA team.

PS: If you have any questions you can join our development server for JDA and we can help you learn more! (our server: [discord.gg/0hMr4ce0tIk3pSjp](https://discord.gg/0hMr4ce0tIk3pSjp))

**Comment by zekroTJA** [comment]
Thanks for the hint ^^ I've updated it not to the latest version (also in my tutorial bot). :)
