### ISSUE TITLE
Userinfo Bug

### ISSUE THREAD

**Issue by Skillkiller** [zekroTJA/DiscordBot#11]
Hallo,
der **userinfo** Command hat einen Fehler, es ist derzeit nicht möglich die Userinfo's von Annondir#7129 zu kommen. Er selbst kommt auch nicht an seine Informationen heran.
Zur besseren Verständnis habe ich hier 2 Bilder hinzugeüfgt:
![Screenshot](http://share.thecoin.de/2017-06-25_17-02-07.png)
![Screenshot](http://share.thecoin.de/2017-06-25_17-02-30.png)

Auch bei anderen usern die kein Profilbild besitzen, werden keine Informationen mehr angezeigt: Daher ist die *Vermutung* das der Bot einen Error auswirft wenn er Versucht die Profilurl zu ermitteln

**Comment by Skillkiller** [comment]
Der Fehler wird du das Thumbnail setzen ausgelöst. Wenn kein Avatr vorhanden ist, dann wurde trozdem versucht ein Thumbnail von der URL **null** zu laden.
Habe ich in #12 behoben 👍

**Comment by zekroTJA** [comment]
solved with #12
