### ISSUE TITLE
Quote Hilfe falsch

### ISSUE THREAD

**Issue by Skillkiller** [zekroTJA/DiscordBot#18]
# Quote Command Hilfe
Hey, 
Ich selbst hatte keinen Plan wie ich den Quote Befehl zu benutzen habe und habe mich deswegen anhand der Hilfe orientiert. Dabei ist mir aufgefallen das diese Anscheinend falsch zu sein scheint. Wenn ich __-qoute__ eingeben haben kam das ich ein Zeitstempel angeben soll. Nach der Angabe eines Zeitstempels wurde gesagt das die __ID__ nicht gefunden wurde. 

Ist auch alles in deinem Discord Channel nachzulesen in dem Commands Channel

**Comment by zekroTJA** [comment]
fixed in commit 7e4f86011613e25ab5d69e3109ddd6110c4fe285
