### ISSUE TITLE
Musik Command lockchannel

### ISSUE THREAD

**Issue by Skillkiller** [zekroTJA/DiscordBot#19]
Der Musik Command ``lockchannel`` scheint leider Guildenübergreifend zu wirken.
Nach einem Restart des Bots scheint der Lock auf jeder Guilde wieder zu verschwinden.

LG
Skillkiller

**Comment by zekroTJA** [comment]
fixed in commit 7e4f86011613e25ab5d69e3109ddd6110c4fe285
